CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    foldername TEXT NOT NULL
);

ALTER TABLE noteful_notes
    ADD COLUMN
        folderid INTEGER REFERENCES noteful_folders(id);